# Generated by Django 5.2.4 on 2025-07-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('duree_estimee', models.IntegerField(help_text='Durée estimée en heures')),
                ('emission_co2', models.FloatField(help_text='Émissions CO2 estimées en kg')),
                ('port_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_arrivee', to='api.port')),
                ('port_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_depart', to='api.port')),
            ],
        ),
    ]
